module.exports = {
  projects: [
    '<rootDir>/apps/booking-app',
    '<rootDir>/apps/booking/desktop-app',
    '<rootDir>/libs/booking/root/feature-shell',
    '<rootDir>/libs/booking/data-access',
    '<rootDir>/libs/shared/root/data-access',
    '<rootDir>/libs/shared/root/environments',
    '<rootDir>/libs/booking/feature-passenger-info',
    '<rootDir>/libs/booking/feature-flight-search',
    '<rootDir>/apps/booking/mobile-app',
    '<rootDir>/libs/check-in/data-access',
    '<rootDir>/libs/check-in/root/feature-shell',
    '<rootDir>/apps/check-in/desktop-app',
    '<rootDir>/apps/check-in/mobile-app',
    '<rootDir>/libs/shared/seatmap/data-access',
    '<rootDir>/libs/shared/seatmap/feature-seat-listing',
    '<rootDir>/libs/shared/ui-buttons',
    '<rootDir>/libs/shared/util-formatting',
    '<rootDir>/libs/shared/root/styles',
  ],
};
